// Code generated by go2go; DO NOT EDIT.


//line main.go2:1
package main

//line main.go2:1
import (
//line main.go2:1
 "fmt"
//line main.go2:1
 "reflect"
//line main.go2:1
)

//line main.go2:18
func main() {
	fmt.Println(instantiate୦୦Add୦int(1, 2), reflect.TypeOf(instantiate୦୦Add୦int(1, 2)))
	fmt.Println(instantiate୦୦Add୦float64(1.0, 2.0), reflect.TypeOf(instantiate୦୦Add୦float64(1.0, 2.0)))
}
//line main.go2:14
func instantiate୦୦Add୦int(a, b int,) int {
	return a + b
}
//line main.go2:14
func instantiate୦୦Add୦float64(a, b float64,) float64 {
	return a + b
}

//line main.go2:16
type Importable୦ int

//line main.go2:16
var _ = fmt.Errorf
//line main.go2:16
var _ = reflect.Append
